/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./../components/ai-assistant.vue')['default']
    AppFooter: typeof import('./../components/app-footer.vue')['default']
    AppHeader: typeof import('./../components/app-header.vue')['default']
    AppNav: typeof import('./../components/app-nav.vue')['default']
    AppNavbar: typeof import('./../components/app-navbar.vue')['default']
    AppNavFull: typeof import('./../components/app-nav-full.vue')['default']
    Badge: typeof import('./../components/badge.vue')['default']
    Components: typeof import('./../components/index.vue')['default']
    ContributorContent: typeof import('./../components/contributor-content.vue')['default']
    EpisodeContent: typeof import('./../components/episode-content.vue')['default']
    EpisodeItem: typeof import('./../components/episode-item.vue')['default']
    EpisodeMeta: typeof import('./../components/episode-meta.vue')['default']
    NavMenu: typeof import('./../components/navbar/nav-menu.vue')['default']
    NavSearch: typeof import('./../components/navbar/nav-search.vue')['default']
    NotFound: typeof import('./../components/not-found.vue')['default']
    Person: typeof import('./../components/person.vue')['default']
    PersonList: typeof import('./../components/person-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sponsors: typeof import('./../components/sponsors.vue')['default']
  }
}
