// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/app-header.vue')['default']
    Badge: typeof import('./../components/badge.vue')['default']
    EpisodeContent: typeof import('./../components/episode-content.vue')['default']
    EpisodeItem: typeof import('./../components/episode-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Undefined: typeof import('./../components/index.vue')['default']
  }
}
